
local_repository(
    name = "engine",
    path = "../engine"
)

local_repository(
    name = "engine_ext",
    path = "../engine-ext"
)

new_local_repository(
    name = "glfw",
    path = "/usr/local/Cellar/glfw/3.2.1",
    build_file = "../engine/third_party/glfw/BUILD"
)

new_local_repository(
    name = "glm",
    path = "/usr/local/Cellar/glm/0.9.9.2",
    build_file = "../engine/third_party/glm/BUILD"
)

new_local_repository(
    name = "bullet",
    path = "/usr/local/Cellar/bullet/2.87_1",
    build_file = "../engine-ext/third_party/bullet/BUILD"
)

new_local_repository(
    name = "freetype",
    path = "/usr/local/Cellar/freetype/2.9",
    build_file = "../engine-ext/third_party/freetype/BUILD"
)