
cc_library(
	name = "engine",
	srcs = glob(["**/*.cpp"]),
	hdrs = glob(["**/*.h"]),
	deps = [
		"@glfw",
    "//third_party/glm",
    "//third_party/chakracore",
    "//third_party/tinyloader"
	],
	visibility = ["//visibility:public"]
)