
cc_library(
	name = "engine",
	srcs = glob(["*.cpp"]),
	hdrs = glob(["*.h"]),
	deps = [
		"//core",
    "//platform",
    "//input",
    "//jsrt",
    "//physics",
    "//fs",
    "//assets",
    "//render",
    "//ui"
	],
	visibility = ["//visibility:public"]
)