
cc_library(
	name = "engine",
	srcs = glob(["*.cpp"]),
	hdrs = glob(["*.h"]),
	deps = [
		"//engine/core",
    "//engine/platform",
    "//engine/input",
    "//engine/jsrt",
    "//engine/physics",
    "//engine/fs",
    "//engine/assets",
    "//engine/render",
    "//engine/ui"
	],
	visibility = ["//visibility:public"]
)