
cc_library(
	name = "render",
	srcs = glob(["**/*.cpp"]),
	hdrs = glob(["**/*.h"]),
	deps = [
		"//core",
		"//entity",
		"//assets",
		"//platform",
		"//math",
		"//memory"
	],
	visibility = ["//visibility:public"]	
)