
cc_library(
	name = "entity",
	srcs = glob(["**/*.cpp"]),
	hdrs = glob(["**/*.h"]),
	deps = [
		"//engine/core",
		"//engine/math",
		"//engine/memory",
		"//engine/messaging",
		"//third_party/tinyloader"
	],
	visibility = ["//visibility:public"]
)