
cc_library(
	name = "input",
	srcs = glob(["*.cpp"]),
	hdrs = glob(["*.h"]),
	deps = [
		"//engine/core",
		"//engine/platform",
		"//engine/math",
		"//engine/messaging",
	],
	visibility = ["//visibility:public"]
)