
cc_library(
	name = "physics-bullet",
	srcs = glob(["*.cpp"]),
	hdrs = glob(["*.h"]),
	deps = [
		"//engine/core",
		"//engine/entity",
		"//engine/physics",
		"@bullet"
	],
	visibility = ["//visibility:public"]
)