
cc_library(
	name = "ui",
	srcs = glob(["**/*.cpp"]),
	hdrs = glob(["**/*.h"]),
	deps = [
		"//engine/core",
		"//engine/entity",
		"//engine/assets",
		"//engine/platform",
		"//engine/math",
		"//engine/render"
	],
	visibility = ["//visibility:public"]	
)